apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /material
        pathType: Prefix
        backend:
          service:
            name: material-madaurus
            port:
              number: 8080
      - path: /staff
        pathType: Prefix
        backend:
          service:
            name: staff-madaurus
            port:
              number: 8080        