apiVersion: kafka.strimzi.io/v1beta2
kind: kafkaTopic
metadata:
  name: post-creation
  namespace: madaurus

  labels:
    strimzi.io/cluster: kafka-cluster
spec: 
  partitions: 1
  replicas: 1
  config:
    retention.ms: 1800000
    segment.bytes: 62914560    # 60 Mb from bytes
