apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: kafka-user
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: NOTIFICATIONS
          patternType: literal
        operations:
          - Describe
          - Write
          - Read
        host: "*"
      - resource:
          type: group
          name: madaurus
          patternType: literal
        operations:
          - Read
        host: "*"
      # Example Producer Acls for topic madaurus-topic
      - resource:
          type: topic
          name: madaurus-topic
          patternType: literal
        operations:
          - Create
          - Describe
          - Write
        host: "*"
